on:
  workflow_call:
jobs:
  BuildAndRelease:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, b2p]
    container: openjdk:17-jdk-alpine3.14
    # container: adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine
    # container: openjdk:18-jdk-alpine3.15
    # container: openjdk:15-jdk-alpine3.12
    steps:
      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: true   #set-safe-directory option of checkout didn't work
          fetch-depth: 0
          token: ${{ secrets.CRC_GIT_TOKEN }}

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.CRC_GIT_USER }}
          git config --global user.email ${{ secrets.CRC_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      
      - name: CheckGitSubmodule
        run: |
          echo "Check central-common"
          cat .gitmodules | grep central-common > /dev/null
          if [ $? == "0" ]; then
            rm -rf central-common
            git submodule add --force --name central-common https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-common central-common
            echo -e "\e[92m central-common is added \e[0m"
          fi

          echo "Check b2p-common"
          cat .gitmodules | grep b2p-common > /dev/null
          if [ $? == "0" ]; then
            rm -rf b2p-common
            git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common b2p-common
            echo -e "\e[92m b2p-common is added \e[0m"
          fi

          git submodule update --remote -f --init
          git checkout HEAD .gitmodules
        continue-on-error: true

      # - name: GitSubmodule
      #   run: |
      #     git submodule update --remote -f --init
      #     git pull --recurse-submodules
      #     git submodule update --remote --no-fetch --force
      #   continue-on-error: true

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CRC_ACR_REGISTRY }}
          username: ${{ secrets.CRC_ACR_USER }}
          password: ${{ secrets.CRC_ACR_TOKEN }}

      - name: BuildTools
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '3.9.1' #'4.5.7'
          skaffold: '1.39.1'
          # skaffold: '1.17.2' #'1.39.1'
          helm: '3.9.4'
          kubectl: '1.17.8' #'1.20.2'
          yq: '4.7.1'

      - name: SetupGradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
        
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

##### Release overlay/dev
      - name: ManualBuildContainerImage
        # if: github.base_ref == 'deployment' && github.event_name == 'pull_request'
        if: contains( github.ref, 'refs/tags' ) && github.event_name == 'workflow_dispatch'
        run: |
          echo -e "\e[92m START ManualBuildContainerImage \e[0m"
          skaffold build -q --tag ${{ github.ref_name }} > build.json
          IMG_NAME=$(jq -r ".builds[0].imageName" build.json)
          IMG_VERSION=$(echo ${IMG_WITH_TAG}  | cut -d ":" -f 2 | cut -d "@" -f 1)
          echo -e "\e[92m ${IMG_NAME}:${IMG_VERSION} \e[0m"
          echo -e "\e[92m FINISH ManualBuildContainerImage \e[0m"