on:
  workflow_call:
jobs:
  BuildAndRelease:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, crc]
    container: openjdk:17-jdk-alpine3.14
    # container: adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine
    # container: openjdk:18-jdk-alpine3.15
    # container: openjdk:15-jdk-alpine3.12
    steps:
      - uses: actions/checkout@v3

      - name: AddGIT
        run: apk --no-cache add git jq tar openssh

      - uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: 'true'   #set-safe-directory option of checkout didn't work

      - name: GitConfig
        run: |
          git config --global --add safe.directory /__w/crc-${{ secrets.CRC_SERVICENAME }}/crc-${{ secrets.CRC_SERVICENAME }}
          git config --global user.name ${{ secrets.CRC_GIT_USER }}
          git config --global user.email ${{ secrets.CRC_GIT_USER }}@dv.co.th

      # - uses: actions/checkout@v3

      # - name: GitSubmodule
      #   run: |
      #     rm -rf central-common
      #     # git submodule add --force --name central-common https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-common.git central-common 
      #     git submodule add --force --name central-common https://${{ secrets.CRC_GITLAB_USER }}:${{ secrets.CRC_GITLAB_TOKEN }}@gitlab.com/dv-bloc/central-common.git central-common central-common 
      #     git submodule update --remote -f --init
      #     # git submodule add --force --name central-common https://github.com/digital-ventures/crc-common.git central-common
      #     git submodule add --force --name central-common https://gitlab.com/dv-bloc/central-common.git central-common

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CRC_ACR_REGISTRY }}
          username: ${{ secrets.CRC_ACR_USER }}
          password: ${{ secrets.CRC_ACR_TOKEN }}

      - name: BuildTools
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '3.9.1' #'4.5.7'
          # skaffold: '1.39.1'
          skaffold: '1.17.2' #'1.39.1'
          helm: '3.9.4'
          kubectl: '1.17.8' #'1.20.2'
          yq: '4.7.1'

      - name: SetupGradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

##### Release overlay/dev
      - name: ManualBuildContainerImage
        # if: github.base_ref == 'deployment' && github.event_name == 'pull_request'
        if: contains( github.ref, 'refs/tags' ) && github.event_name == 'workflow_dispatch'
        run: |
          echo -e "\e[92m START ManualBuildContainerImage \e[0m"
          skaffold build -q --tag ${{ github.ref_name }} > build.json
          IMG_NAME=$(jq -r ".builds[0].imageName" build.json)
          IMG_VERSION=$(echo ${IMG_WITH_TAG}  | cut -d ":" -f 2 | cut -d "@" -f 1)
          echo -e "\e[92m ${IMG_NAME}:${IMG_VERSION} \e[0m"
          echo -e "\e[92m FINISH ManualBuildContainerImage \e[0m"