on:
  workflow_call:
  workflow_run:
    workflows: ["Build"]
    branches:
      - 'deployment'
      - '**release**'
    tags-ignore:
      - ""
      - '!**Gradle Release Plugin**'
  pull_request_target:
    branches-ignore:
      - 'deployment'
  push: 
    paths:
      - gradle/**/*
      - manifests/**/*
      - src/**/*
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
      - skaffold.yml

jobs:
  test:
    name: test
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/master' || contains( github.ref_name, 'CRC' ) || contains( github.ref_name, 'production' ) || contains( github.ref_name, 'SONAR' )
    uses: digital-ventures/crc-ci-libraries/.github/workflows/ci-backend-test.yaml@master
    secrets: inherit
  release:
    name: release
    uses: digital-ventures/crc-ci-libraries/.github/workflows/ci-backend-build.yaml@master
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/deployment' || github.ref_type == 'tag'
    secrets: inherit

